### PR TITLE
post-'landing page' update, class config preview rework

### PR DESCRIPTION
**Pull request by xiyzzc**
Hi mkrl, nice work on the recent additions the site. It's looking really good.
I've been working on some stuff, all the commits are separate and easy to digest. I hope none of my edits ruin anything you felt strongly about, I tried to be as objective as possible with my edits. Tested on firefox and chrome.

Here's a basic rundown:
- The footer was reworked with proper bootstrap columns so that its responsive on small screens
- On the new front page, I just moved the quotes to the top (thought it looked better to be upfront with it) and reworked the inline styling a bit with bootstrap classes. Also added "client/server" titles to the big buttons.
- **Config preview rework. Configs currently have a slideshow of 5 pl_badwater images, and pros/cons are 2 columns underneath. (I plan to add slideshows for many maps and include item effects and stuff like the originals. Currently just an uber demonstration and all the checkpoints. Previews don't have glow outline enabled, I might need to fix that up later).**
- Added some more configs, along with the necessary updatedxlevel() triggers and such. (Need more pros/cons for these).
- Config images are lazy loaded with `unveil.js` so that the user doesn't download them all at once. Loading triggers from the dropdown selection. Check here for docs https://luis-almeida.github.io/unveil/
- Changed some `text-muted` paragraphs into alerts. Vital info shouldn't be "muted," only superfluous info should.
- There's a version.txt in /make and /server that feed the version number to their respective page. Please use these to bump the version number up whenever you like, it saves you from constantly editing the index.html even if other files caused the version bump.
- Theme files are pulled from CDN and the customisations were put in main.css. I'm not sure exactly how much you edited the flatly theme from default, but I'm pretty sure I got all your additions.
- Changed any inline themeing to bootstrap classes / main.css.
- Fixed any absolute paths I found.

### CODE REVIEW

**Comment by mkrl** [comment]
You're doing a huge part of the work I was planning to do, I can't thank you enough. If everything works fine, I will merge this soon. Also, if you are planning to contribute more, you might want to join our Discord where I can give you an access to the dev chat so we can discuss major changes that may overwrite each other and also just talk in general https://discord.gg/79cbsTu . Hit me up if you decide to join.

**Comment by mkrl** [comment]
Very nice work, merged. I will make an additional commit to fix a few bugs and add a bit more functionality.

**Comment by mkrl** [comment]
Whoops, looks like I've reverted your last pack of commits with mine, didn't expect you to commit more that soon. I've fixed the slider from your previous commit. Will try to fix rest when I get back home.

**Comment by xiyzzc** [comment]
Sorry I thought it just did the commits from when I did the pull request, not everything I commit. I'll look into getting on discord soon so we can stop tripping over each other.

**Comment by mkrl** [comment]
No problem. I restored your changes and merged our commits, should be fine now.

**Pull request merged**
